### ISSUE TITLE
Help me bikeshed the gauge look

### ISSUE THREAD

**Issue by iarna** [npm/gauge#36]
You can see a demo of the current theme for various levels of OS/unicode/color support here:

https://twitter.com/ReBeccaOrg/status/701336143686578176

Or try running `demo.js` from the repo.  2.0, which has this is in beta. Right now changing this up is easy and cheap, so help me paint this bikeshed.

**Comment by iarna** [comment]
Mentioned elsewhere:

https://github.com/sindresorhus/elegant-spinner
https://github.com/helloIAmPau/node-spinner/blob/master/index.js#L13-L32

**Comment by Fishrock123** [comment]
Hmmm, maybe there could also be some sort of percentage display?

Being able to define spinner animations could definitely be cool. I quite like elegant-spinner. Could even be configurable in some npm config?

## 

I'm quite wondering how it might be best to deal with sub-jobs, or concurrency. [`pnpm`](https://github.com/rstacruz/pnpm) has a pretty cool display of concurrency, for example. Perhaps that is out of scope though.

I suppose to some degree, sub-jobs is up to the implementing application to handle correctly?

## 

Edit: fwiw I previously made https://github.com/Fishrock123/cli-status (Not very good, please don't use it lol)

**Comment by iarna** [comment]
Sub-job tracking / concurrency is probably out of scope for this module yeah, since this is just about drawing bars on the screen. npm has a pretty good handle on what's going on via `are-we-there-yet` trees, but we aren't exposing that currently.

But there's no reason that `npm` couldn't setup an arbitrarily complicated `gauge` theme to track that kind of thing. (In `gauge@1`, you could only pass in section/subsection text, but in `gauge@2` you can pass in arbitrary values, and if they're in the theme they'll be displayed.)

TBH, I'm not actually convinced how valuable that is.  `npm` side the main thing I'd like to see is real network-layer support. That is, I'd like it to be using `are-we-there-yet` stream objects to track download completion instead of just starting a timed spinner.

**Comment by iarna** [comment]
If we end up really wanting to track concurrent jobs we might also look at supporting multi-line statuses.

The advantage of single line status areas is that you can update them without using any ansi codes– just CR and go.

**Comment by yongtw123** [comment]
2nd edit: Remove unnecessary information

I'd like to report on Win 7 (CJK code page) the new gauge seems to work on default `cmd`. However when I tested on a terminal emulator (i.e. ConEmu), new gauge lines keep printing one after another. The situation goes away mostly when the current theme is 'nocolor'.
![colornocolor](https://cloud.githubusercontent.com/assets/1749977/13241934/a9a59016-da2a-11e5-8d2e-ae1cc9f22a1e.gif)
Since I expect at least non-unicode themes to work under Windows environment, I looked into `theme.js` and noticed `themes.fallback.noUnicode.hasColor.remaining` (░) seems not a pure ANSI character. After changing it to any other pure ASCII character (not including the extended ones), the issue is gone, at least for non-`darwin` themes.

Perhaps I'd suggest sticking to pure ASCII for non-Unicode themes to maximize compatibility?

By the way, running `demo.js` requires a dependency which is not in `package.json`: `signal-exit`.

**Comment by gillesdemey** [comment]
I'm a big fan of the elegant spinner for terminals that support unicode (using braille characters), I don't have a strong preference for the ascii spinner.

Are we permanently moving the bar to the left? If so :+1: since that was a pain point with v1 where the text would get obfuscated by the progress bar.

The new spinner seems to work fine with the ambiguous width option, I'll give the demo a spin on some of my VMs when I get to it :)

**Comment by iarna** [comment]
@gillesdemey Yeah, the braile spinners are keen, but mac only. But we can actually do that now.

**Comment by iarna** [comment]
@yongtw123 Thanks for the report! I'll do some testing in ConEmu. Also you're totally right about `░` not belonging in a non-unicode theme.

(Mind, those are the `darwin` (read: MacOS) part of the demo you're seeing there.

**Comment by gillesdemey** [comment]
Last time I tested, the braille characters worked fine on Ubuntu. Not too sure about other distros.

**Comment by iarna** [comment]
It was Ubuntu I last tested on, but it was over a year ago so it may be getting better.

**Comment by iarna** [comment]
I'm not opposed to using braille spinners on unicode-aware Linux distros if the support is there (I just want to avoid too many people seeing � in the installer =p).

**Comment by iarna** [comment]
Ok, to update the "can we use fancy braille on Linux distros" thread:

I've tested on the latest Ubuntu and Fedora. They're quite lovely on the former and super ugly on the latter (due to font selection).

But there's a further wrinkle which will means that this theme **can't be the default** for Ubuntu:

**If I'm sshed into an Ubuntu box, there's no way to know what unicode my terminal will support.**

Overriding themes w/ the new gauge is easy (and they're named now, so you can say you want the `colorBrailleSpinner` theme and get that). Access to theming will be exposed all the way up the chain with it, so expect that to show up in `npmlog` and `npm` when we integrate this version.

**Comment by iarna** [comment]
@yongtw123 I can't reproduce your issue with ConEmu– can you try again with the latest updates?

(It may be that some themes don't work on Windows, the errors you were seeing were from the theme used for MacOS. Windows will ordinarily get what's now called the `colorASCII` theme by default.

**Comment by yongtw123** [comment]
@iarna Awesome! The ASCII themes seem to work correctly on my system and ConEmu. Thanks for the update.
ConEmu
![2 2 1](https://cloud.githubusercontent.com/assets/1749977/13799761/7364d964-eb5d-11e5-906b-33ee4f99502b.gif)
Default CMD
![2 2 1cmd](https://cloud.githubusercontent.com/assets/1749977/13799872/668efaf2-eb5e-11e5-8030-820746a6373a.gif)

**Comment by iarna** [comment]
Ok, this all landed and is looking good. I'm going to close this and we can open something new if we want to iterate further.
