### ISSUE TITLE
Debounce pulses?

### ISSUE THREAD

**Issue by williamboman** [npm/gauge#7]
Would probably help with stuff like https://github.com/npm/npm/issues/8826#issuecomment-155762361

**Comment by iarna** [comment]
`show()` has debounce code, but eeeeeh, it's churning timers currently. I intend to rewrite things such that the progress bar is drawn on a straight interval timer, with `show()` and `pulse()` just updating info on what should be printed when the interval comes.

**Comment by iarna** [comment]
I have a rewrite underway that switches to a timesliced mechanism (eg, every 50ms, update the progress bar) rather than something triggered by calls to pulse or show, that will eliminate these issues and makes all of this waaay simpler.

If you're curious, you can see the in-progress branch, which is still has lots of unsquashed wip commits over here:
https://github.com/iarna/gauge/tree/new-rewrite

(It's feature complete, I'm just tightening up test coverage and rewriting docs now.)
